FROM node:18-alpine AS build

RUN npm i -g pnpm

WORKDIR /app
COPY package.json /app
RUN pnpm config set registry https://registry.npmjs.org
RUN pnpm config set fetch-retries 5
RUN pnpm config set fetch-timeout 60000
RUN apk add --no-cache chromium && \
    pnpm i

COPY . /app

EXPOSE 3000/tcp

CMD ["pnpm", "dev"]



